// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gerencia.Model;

#nullable disable

namespace gerencia.Migrations
{
    [DbContext(typeof(EventosContext))]
    partial class EventosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("GuestUsuario", b =>
                {
                    b.Property<int>("ConvidadoEmEventosIdGuest")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConvidadosIdUsuario")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConvidadoEmEventosIdGuest", "ConvidadosIdUsuario");

                    b.HasIndex("ConvidadosIdUsuario");

                    b.ToTable("GuestUsuario");
                });

            modelBuilder.Entity("gerencia.Model.Evento", b =>
                {
                    b.Property<int>("IdEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CriadorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("Horario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Privacidade")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdEvento");

                    b.HasIndex("CriadorId");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("gerencia.Model.Guest", b =>
                {
                    b.Property<int>("IdGuest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IdEvento")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdGuest");

                    b.HasIndex("IdEvento");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("gerencia.Model.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Email");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("GuestUsuario", b =>
                {
                    b.HasOne("gerencia.Model.Guest", null)
                        .WithMany()
                        .HasForeignKey("ConvidadoEmEventosIdGuest")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gerencia.Model.Usuario", null)
                        .WithMany()
                        .HasForeignKey("ConvidadosIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("gerencia.Model.Evento", b =>
                {
                    b.HasOne("gerencia.Model.Usuario", "Criador")
                        .WithMany()
                        .HasForeignKey("CriadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Criador");
                });

            modelBuilder.Entity("gerencia.Model.Guest", b =>
                {
                    b.HasOne("gerencia.Model.Evento", "Evento")
                        .WithMany("Guests")
                        .HasForeignKey("IdEvento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("gerencia.Model.Evento", b =>
                {
                    b.Navigation("Guests");
                });
#pragma warning restore 612, 618
        }
    }
}
